version: '3.8'
services:
  invoice-database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "P@ssword123"
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"